//logger.info("testing dynamically changing threads.");
print('waiting 500 ms');
scenario.waitMillis(500);
print('waited');
scenario.start('type=diag;alias=threadchange;cycles=0..100000000;threads=1;interval=2000;modulo=1000000');
//activities.threadchange.threads=1;
activities.threadchange.threads=5;
print('waiting 1000 ms');
scenario.waitMillis(1000);
activities.threadchange.threads=20;
//activities.threadchange.threads=1;
activities.threadchange.interval=100;
print('waiting 1000 ms');
scenario.waitMillis(1000);
scenario.stop('threadchange');
