@startuml
title Creating Dispensers for an Activity Instance

Executor -> Assembler: getMotorDispenser(ActivityDef)

alt ActivityType provides inputs
 Assembler -> Activity : getInputDispenser(ActivityDef)
 Assembler <- Activity : <inputDispenser>
else core provides inputs
 Assembler -> CoreRuntime : create CoreInputDispenser(ActivityDef)
 Assembler <- CoreRuntime : <coreInputDispenser>
end

alt ActivityType provides actions
 Assembler -> Activity : getActionDispenser(ActivityDef)
 Assembler <- Activity : <actionDispenser>
else core provides actions
 Assembler -> CoreRuntime : create CoreActionDispenser(ActivityDef)
 Assembler <- CoreRuntime : <coreActionDispenser>
end

alt ActivityType provides motors
 Assembler -> Activity : getMotorDispenser(ActivityDef,<dispensers>)
 Assembler <- Activity : <motorDispenser>
else core provides motors
 Assembler -> CoreRuntime : create CoreMotorDispenser(ActivityDef,<dispensers>)
 Assembler <- CoreRuntime : <coreMotorDispenser>
end

Executor <- Assembler: <motorDispenser>

@enduml